export { Hero } from "./hero"
export { TrustedBySection } from "./features-scroll"
export { Feature } from "./features"
export { Services } from "./services"
export { Pricing } from "./pricing"
export { BeforeAfterSection } from "./beforeAfterSection"
export { FinalCTA } from "./FinalCTA"
export { SquareIntegrationHomepage } from "./SquareIntegrationHomepage"
