// allergenIcons.ts

import { Egg, Fish, Leaf, Apple, Carrot, Wine, Coffee, Drumstick, PiggyBank, AlertTriangle, HelpCircle, FlaskConical, Flower, Bean, Layers, Nut, Grape } from "lucide-react"

export const allergenIconMap: Record<string, JSX.Element> = {
  gluten: <Layers className="mr-1 inline-block" />,
  wheat: <Layers className="mr-1 inline-block" />,
  barley: <Layers className="mr-1 inline-block" />,
  rye: <Layers className="mr-1 inline-block" />,
  oats: <Layers className="mr-1 inline-block" />,
  spelt: <Layers className="mr-1 inline-block" />,
  kamut: <Layers className="mr-1 inline-block" />,
  crustaceans: <Fish className="mr-1 inline-block" />,
  shrimp: <Fish className="mr-1 inline-block" />,
  prawns: <Fish className="mr-1 inline-block" />,
  crab: <Fish className="mr-1 inline-block" />,
  lobster: <Fish className="mr-1 inline-block" />,
  crayfish: <Fish className="mr-1 inline-block" />,
  eggs: <Egg className="mr-1 inline-block" />,
  egg: <Egg className="mr-1 inline-block" />,
  fish: <Fish className="mr-1 inline-block" />,
  salmon: <Fish className="mr-1 inline-block" />,
  tuna: <Fish className="mr-1 inline-block" />,
  cod: <Fish className="mr-1 inline-block" />,
  sardines: <Fish className="mr-1 inline-block" />,
  anchovies: <Fish className="mr-1 inline-block" />,
  peanuts: <Nut className="mr-1 inline-block" />,
  peanut: <Nut className="mr-1 inline-block" />,
  groundnuts: <Nut className="mr-1 inline-block" />,
  soy: <Bean className="mr-1 inline-block" />,
  soya: <Bean className="mr-1 inline-block" />,
  soybeans: <Bean className="mr-1 inline-block" />,
  milk: <FlaskConical className="mr-1 inline-block" />,
  dairy: <FlaskConical className="mr-1 inline-block" />,
  lactose: <FlaskConical className="mr-1 inline-block" />,
  cheese: <FlaskConical className="mr-1 inline-block" />,
  butter: <FlaskConical className="mr-1 inline-block" />,
  cream: <FlaskConical className="mr-1 inline-block" />,
  yogurt: <FlaskConical className="mr-1 inline-block" />,
  yoghurt: <FlaskConical className="mr-1 inline-block" />,
  nuts: <Nut className="mr-1 inline-block" />,
  almonds: <Nut className="mr-1 inline-block" />,
  hazelnuts: <Nut className="mr-1 inline-block" />,
  walnuts: <Nut className="mr-1 inline-block" />,
  cashews: <Nut className="mr-1 inline-block" />,
  pecans: <Nut className="mr-1 inline-block" />,
  brazil: <Nut className="mr-1 inline-block" />,
  pistachios: <Nut className="mr-1 inline-block" />,
  macadamia: <Nut className="mr-1 inline-block" />,
  chestnuts: <Nut className="mr-1 inline-block" />,
  celery: <Leaf className="mr-1 inline-block" />,
  celeriac: <Leaf className="mr-1 inline-block" />,
  sesame: <Layers className="mr-1 inline-block" />,
  sulphites: <FlaskConical className="mr-1 inline-block" />,
  sulfites: <FlaskConical className="mr-1 inline-block" />,
  sulphur: <FlaskConical className="mr-1 inline-block" />,
  lupin: <Flower className="mr-1 inline-block" />,
  lupine: <Flower className="mr-1 inline-block" />,
  molluscs: <Fish className="mr-1 inline-block" />,
  mollusks: <Fish className="mr-1 inline-block" />,
  mussels: <Fish className="mr-1 inline-block" />,
  clams: <Fish className="mr-1 inline-block" />,
  oysters: <Fish className="mr-1 inline-block" />,
  scallops: <Fish className="mr-1 inline-block" />,
  squid: <Fish className="mr-1 inline-block" />,
  octopus: <Fish className="mr-1 inline-block" />,
  snails: <Fish className="mr-1 inline-block" />,
  apple: <Apple className="mr-1 inline-block" />,
  apples: <Apple className="mr-1 inline-block" />,
  strawberry: <Apple className="mr-1 inline-block" />,
  strawberries: <Apple className="mr-1 inline-block" />,
  kiwi: <Apple className="mr-1 inline-block" />,
  pineapple: <Apple className="mr-1 inline-block" />,
  banana: <Apple className="mr-1 inline-block" />,
  bananas: <Apple className="mr-1 inline-block" />,
  peach: <Apple className="mr-1 inline-block" />,
  peaches: <Apple className="mr-1 inline-block" />,
  cherry: <Apple className="mr-1 inline-block" />,
  cherries: <Apple className="mr-1 inline-block" />,
  grapes: <Grape className="mr-1 inline-block" />,
  avocado: <Apple className="mr-1 inline-block" />,
  citrus: <Apple className="mr-1 inline-block" />,
  orange: <Apple className="mr-1 inline-block" />,
  lemon: <Apple className="mr-1 inline-block" />,
  lime: <Apple className="mr-1 inline-block" />,
  grapefruit: <Apple className="mr-1 inline-block" />,
  mango: <Apple className="mr-1 inline-block" />,
  papaya: <Apple className="mr-1 inline-block" />,
  melon: <Apple className="mr-1 inline-block" />,
  watermelon: <Apple className="mr-1 inline-block" />,
  tomato: <Carrot className="mr-1 inline-block" />,
  tomatoes: <Carrot className="mr-1 inline-block" />,
  potato: <Carrot className="mr-1 inline-block" />,
  potatoes: <Carrot className="mr-1 inline-block" />,
  carrot: <Carrot className="mr-1 inline-block" />,
  carrots: <Carrot className="mr-1 inline-block" />,
  garlic: <Leaf className="mr-1 inline-block" />,
  corn: <Carrot className="mr-1 inline-block" />,
  maize: <Carrot className="mr-1 inline-block" />,
  bell_pepper: <Carrot className="mr-1 inline-block" />,
  peppers: <Carrot className="mr-1 inline-block" />,
  cucumber: <Leaf className="mr-1 inline-block" />,
  lettuce: <Leaf className="mr-1 inline-block" />,
  spinach: <Leaf className="mr-1 inline-block" />,
  broccoli: <Leaf className="mr-1 inline-block" />,
  cauliflower: <Leaf className="mr-1 inline-block" />,
  cabbage: <Leaf className="mr-1 inline-block" />,
  ginger: <Carrot className="mr-1 inline-block" />,
  parsley: <Leaf className="mr-1 inline-block" />,
  basil: <Leaf className="mr-1 inline-block" />,
  oregano: <Leaf className="mr-1 inline-block" />,
  thyme: <Leaf className="mr-1 inline-block" />,
  rosemary: <Leaf className="mr-1 inline-block" />,
  dill: <Leaf className="mr-1 inline-block" />,
  mint: <Leaf className="mr-1 inline-block" />,
  beans: <Bean className="mr-1 inline-block" />,
  lentils: <Bean className="mr-1 inline-block" />,
  chickpeas: <Bean className="mr-1 inline-block" />,
  peas: <Bean className="mr-1 inline-block" />,
  lima_beans: <Bean className="mr-1 inline-block" />,
  kidney_beans: <Bean className="mr-1 inline-block" />,
  black_beans: <Bean className="mr-1 inline-block" />,
  beef: <PiggyBank className="mr-1 inline-block" />,
  pork: <PiggyBank className="mr-1 inline-block" />,
  chicken: <Drumstick className="mr-1 inline-block" />,
  turkey: <Drumstick className="mr-1 inline-block" />,
  lamb: <Drumstick className="mr-1 inline-block" />,
  duck: <Drumstick className="mr-1 inline-block" />,
  chocolate: <Coffee className="mr-1 inline-block" />,
  cocoa: <Coffee className="mr-1 inline-block" />,
  coffee: <Coffee className="mr-1 inline-block" />,
  tea: <Leaf className="mr-1 inline-block" />,
  alcohol: <Wine className="mr-1 inline-block" />,
  wine: <Wine className="mr-1 inline-block" />,
  beer: <Wine className="mr-1 inline-block" />,
  yeast: <FlaskConical className="mr-1 inline-block" />,
  vinegar: <FlaskConical className="mr-1 inline-block" />,
  msg: <FlaskConical className="mr-1 inline-block" />,
  artificial_colors: <FlaskConical className="mr-1 inline-block" />,
  artificial_flavors: <FlaskConical className="mr-1 inline-block" />,
  preservatives: <FlaskConical className="mr-1 inline-block" />,
  aspartame: <FlaskConical className="mr-1 inline-block" />,
  tartrazine: <FlaskConical className="mr-1 inline-block" />,
  benzoates: <FlaskConical className="mr-1 inline-block" />,
  nitrates: <FlaskConical className="mr-1 inline-block" />,
  sunflower_seeds: <Nut className="mr-1 inline-block" />,
  pumpkin_seeds: <Nut className="mr-1 inline-block" />,
  poppy_seeds: <Nut className="mr-1 inline-block" />,
  flax_seeds: <Nut className="mr-1 inline-block" />,
  chia_seeds: <Nut className="mr-1 inline-block" />,
  rice: <Layers className="mr-1 inline-block" />,
  buckwheat: <Layers className="mr-1 inline-block" />,
  quinoa: <Layers className="mr-1 inline-block" />,
  amaranth: <Layers className="mr-1 inline-block" />,
  coconut: <Nut className="mr-1 inline-block" />,
  gelatin: <FlaskConical className="mr-1 inline-block" />,
  carrageenan: <FlaskConical className="mr-1 inline-block" />,
  latex: <FlaskConical className="mr-1 inline-block" />,
  birch_pollen: <Flower className="mr-1 inline-block" />,
  ragweed_pollen: <Flower className="mr-1 inline-block" />,
  grass_pollen: <Flower className="mr-1 inline-block" />,
  unknown: <HelpCircle className="mr-1 inline-block" />,
  other: <AlertTriangle className="mr-1 inline-block" />,
  default: <AlertTriangle className="mr-1 inline-block" />,
}

export const getAllergenIcon = (allergen: string): JSX.Element => {
  const normalizedAllergen = allergen.toLowerCase().replace(/\s+/g, "_")
  return allergenIconMap[normalizedAllergen] || allergenIconMap.default
}

// Categories for easier management
export const allergenCategories = {
  ukMajor14: [
    "gluten",
    "crustaceans",
    "eggs",
    "fish",
    "peanuts",
    "soy",
    "milk",
    "nuts",
    "celery",
    "mustard",
    "sesame",
    "sulphites",
    "lupin",
    "molluscs",
  ],
  fruits: [
    "apple",
    "strawberry",
    "kiwi",
    "pineapple",
    "banana",
    "peach",
    "cherry",
    "grapes",
    "avocado",
    "citrus",
    "mango",
    "papaya",
  ],
  vegetables: [
    "tomato",
    "potato",
    "carrot",
    "onion",
    "garlic",
    "corn",
    "peppers",
    "cucumber",
    "lettuce",
    "spinach",
  ],
  spices: ["ginger", "turmeric", "cumin", "coriander", "cinnamon", "nutmeg", "paprika", "vanilla"],
  legumes: ["beans", "lentils", "chickpeas", "peas", "lima_beans", "kidney_beans", "black_beans"],
  additives: [
    "msg",
    "artificial_colors",
    "artificial_flavors",
    "preservatives",
    "aspartame",
    "tartrazine",
    "benzoates",
    "nitrates",
  ],
}
