const allergenColorMap: Record<string, string> = {
  // === UK 14 Major Allergens ===
  gluten: "text-orange-500",
  wheat: "text-orange-500",
  barley: "text-orange-500",
  rye: "text-orange-500",
  oats: "text-orange-500",
  spelt: "text-orange-500",
  kamut: "text-orange-500",

  crustaceans: "text-red-500",
  shrimp: "text-red-500",
  prawns: "text-red-500",
  crab: "text-red-500",
  lobster: "text-red-500",
  crayfish: "text-red-500",

  eggs: "text-yellow-500",
  egg: "text-yellow-500",

  fish: "text-teal-500",
  salmon: "text-teal-500",
  tuna: "text-teal-500",
  cod: "text-teal-500",
  sardines: "text-teal-500",
  anchovies: "text-teal-500",

  peanuts: "text-brown-500",
  peanut: "text-brown-500",
  groundnuts: "text-brown-500",

  soy: "text-green-500",
  soya: "text-green-500",
  soybeans: "text-green-500",

  milk: "text-purple-500",
  dairy: "text-purple-500",
  lactose: "text-purple-500",
  cheese: "text-purple-500",
  butter: "text-purple-500",
  cream: "text-purple-500",
  yogurt: "text-purple-500",
  yoghurt: "text-purple-500",

  nuts: "text-amber-600",
  almonds: "text-amber-600",
  hazelnuts: "text-amber-600",
  walnuts: "text-amber-600",
  cashews: "text-amber-600",
  pecans: "text-amber-600",
  brazil: "text-amber-600",
  pistachios: "text-amber-600",
  macadamia: "text-amber-600",
  chestnuts: "text-amber-600",

  celery: "text-lime-600",
  celeriac: "text-lime-600",

  mustard: "text-yellow-600",

  sesame: "text-amber-500",
  sesame_seeds: "text-amber-500",

  sulphites: "text-gray-500",
  sulfites: "text-gray-500",
  sulphur: "text-gray-500",

  lupin: "text-pink-500",
  lupine: "text-pink-500",

  molluscs: "text-purple-600",
  mollusks: "text-purple-600",
  mussels: "text-purple-600",
  clams: "text-purple-600",
  oysters: "text-purple-600",
  scallops: "text-purple-600",
  squid: "text-purple-600",
  octopus: "text-purple-600",
  snails: "text-purple-600",

  // === Fruits ===
  apple: "text-rose-500",
  apples: "text-rose-500",
  strawberry: "text-rose-600",
  strawberries: "text-rose-600",
  kiwi: "text-green-600",
  pineapple: "text-yellow-600",
  banana: "text-yellow-500",
  bananas: "text-yellow-500",
  peach: "text-orange-400",
  peaches: "text-orange-400",
  cherry: "text-red-600",
  cherries: "text-red-600",
  grapes: "text-purple-500",
  avocado: "text-green-700",
  citrus: "text-yellow-500",
  orange: "text-orange-500",
  lemon: "text-yellow-400",
  lime: "text-green-500",
  grapefruit: "text-orange-500",
  mango: "text-orange-500",
  papaya: "text-orange-500",

  // === Vegetables ===
  tomato: "text-red-500",
  potatoes: "text-yellow-700",
  potato: "text-yellow-700",
  carrot: "text-orange-400",
  carrots: "text-orange-400",
  garlic: "text-gray-500",
  corn: "text-yellow-400",
  maize: "text-yellow-400",
  peppers: "text-red-500",
  bell_pepper: "text-red-500",
  cucumber: "text-green-500",
  lettuce: "text-green-500",
  spinach: "text-green-600",
  broccoli: "text-green-700",
  cauliflower: "text-green-400",
  cabbage: "text-green-500",

  // === Spices ===
  ginger: "text-amber-500",
  turmeric: "text-yellow-500",
  cumin: "text-brown-500",
  coriander: "text-green-500",
  cinnamon: "text-brown-600",
  nutmeg: "text-brown-600",
  paprika: "text-red-600",
  vanilla: "text-yellow-400",

  // === Legumes ===
  beans: "text-green-500",
  lentils: "text-orange-500",
  chickpeas: "text-yellow-600",
  peas: "text-green-400",
  lima_beans: "text-green-400",
  kidney_beans: "text-red-500",
  black_beans: "text-black",

  // === Additives ===
  msg: "text-gray-500",
  artificial_colors: "text-gray-500",
  artificial_flavors: "text-gray-500",
  preservatives: "text-gray-500",
  aspartame: "text-gray-500",
  tartrazine: "text-gray-500",
  benzoates: "text-gray-500",
  nitrates: "text-gray-500",

  // === Meats ===
  meat: "text-pink-500",
  beef: "text-pink-600",
  pork: "text-pink-500",
  chicken: "text-orange-400",
  turkey: "text-orange-400",
  lamb: "text-pink-600",
  duck: "text-pink-600",

  // === fallback ===
  unknown: "text-gray-500",
  other: "text-gray-500",
  default: "text-gray-500",
}

export default allergenColorMap
